version: '3'
services:
  web:
    image: django:5.0.1
    container_name: django
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: sh -c "python ./carea/manage.py runserver 0.0.0.0:8000"