# Generated by Django 5.0.1 on 2024-02-11 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
