# Generated by Django 5.0.1 on 2024-01-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('profile_url', models.CharField(blank=True, max_length=255, null=True)),
                ('introduction', models.CharField(blank=True, max_length=100, null=True)),
                ('point', models.IntegerField(default=0)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
