# Generated by Django 5.0.1 on 2024-02-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helps', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='latitude',
            field=models.DecimalField(decimal_places=12, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='help',
            name='longitude',
            field=models.DecimalField(decimal_places=12, default=0.0, max_digits=15),
        ),
    ]
