# Generated by Django 5.0.1 on 2024-02-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helps', '0003_help_latitude_help_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
