# Generated by Django 5.0.1 on 2024-02-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helps', '0004_alter_help_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
